/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreateRoomRouteImport } from './routes/create-room'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as MainRegisterRouteImport } from './routes/_main/register'
import { Route as MainLoginRouteImport } from './routes/_main/login'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomRoute = CreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRegisterRoute = MainRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MainRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/battles': typeof BattlesRoute
  '/create-room': typeof CreateRoomRoute
  '/profile': typeof ProfileRoute
  '/login': typeof MainLoginRoute
  '/register': typeof MainRegisterRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/battles': typeof BattlesRoute
  '/create-room': typeof CreateRoomRoute
  '/profile': typeof ProfileRoute
  '/login': typeof MainLoginRoute
  '/register': typeof MainRegisterRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/battles': typeof BattlesRoute
  '/create-room': typeof CreateRoomRoute
  '/profile': typeof ProfileRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/register': typeof MainRegisterRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battles'
    | '/create-room'
    | '/profile'
    | '/login'
    | '/register'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/battles'
    | '/create-room'
    | '/profile'
    | '/login'
    | '/register'
    | '/rooms/$roomId'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/battles'
    | '/create-room'
    | '/profile'
    | '/_main/login'
    | '/_main/register'
    | '/rooms/$roomId'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  BattlesRoute: typeof BattlesRoute
  CreateRoomRoute: typeof CreateRoomRoute
  ProfileRoute: typeof ProfileRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/register': {
      id: '/_main/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainRegisterRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainLoginRoute: typeof MainLoginRoute
  MainRegisterRoute: typeof MainRegisterRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainLoginRoute: MainLoginRoute,
  MainRegisterRoute: MainRegisterRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  BattlesRoute: BattlesRoute,
  CreateRoomRoute: CreateRoomRoute,
  ProfileRoute: ProfileRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
