/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appCreateRoomRouteImport } from './routes/(app)/create-room'
import { Route as appBattlesRouteImport } from './routes/(app)/battles'
import { Route as appRoomsRoomIdRouteImport } from './routes/(app)/rooms/$roomId'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appCreateRoomRoute = appCreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => appRouteRoute,
} as any)
const appBattlesRoute = appBattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => appRouteRoute,
} as any)
const appRoomsRoomIdRoute = appRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/battles': typeof appBattlesRoute
  '/create-room': typeof appCreateRoomRoute
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof appIndexRoute
  '/rooms/$roomId': typeof appRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/battles': typeof appBattlesRoute
  '/create-room': typeof appCreateRoomRoute
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof appIndexRoute
  '/rooms/$roomId': typeof appRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/battles': typeof appBattlesRoute
  '/(app)/create-room': typeof appCreateRoomRoute
  '/(app)/profile': typeof appProfileRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/rooms/$roomId': typeof appRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/battles'
    | '/create-room'
    | '/profile'
    | '/login'
    | '/register'
    | '/'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/battles'
    | '/create-room'
    | '/profile'
    | '/login'
    | '/register'
    | '/'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(app)/battles'
    | '/(app)/create-room'
    | '/(app)/profile'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(app)/'
    | '/(app)/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/create-room': {
      id: '/(app)/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof appCreateRoomRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/battles': {
      id: '/(app)/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof appBattlesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/rooms/$roomId': {
      id: '/(app)/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof appRoomsRoomIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appBattlesRoute: typeof appBattlesRoute
  appCreateRoomRoute: typeof appCreateRoomRoute
  appProfileRoute: typeof appProfileRoute
  appIndexRoute: typeof appIndexRoute
  appRoomsRoomIdRoute: typeof appRoomsRoomIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appBattlesRoute: appBattlesRoute,
  appCreateRoomRoute: appCreateRoomRoute,
  appProfileRoute: appProfileRoute,
  appIndexRoute: appIndexRoute,
  appRoomsRoomIdRoute: appRoomsRoomIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
